package models

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// GeneratePresetINI creates a llama.cpp preset INI file from the model
// registry. Each model gets a section with per-model settings.
//
// Section names use the registry ID, which is unique per model (one entry
// per quant file). The earlier dirname-based scheme collided whenever a
// repo directory held multiple quants — INI sections sharing a name get
// merged by llama.cpp's parser, silently dropping every quant past the
// first. The aliases line still lists the dirname plus the public short
// name and any user aliases, so callers can address a model by any of them.
// The router runs with --models-preset only (no --models-dir), so we don't
// need the section name to match auto-discovery.
//
// INI keys map directly to llama-server CLI flags with leading dashes removed.
func GeneratePresetINI(modelsDir string, models []*Model, configs map[string]*ModelConfig) string {
	var b strings.Builder

	b.WriteString("# Auto-generated by llama-toolchest — do not edit manually.\n")
	b.WriteString("# Changes here will be overwritten when model configs are saved.\n\n")

	// Track which dirname-aliases collide across multiple models so we can
	// drop them from aliases entirely — listing the same alias on two
	// sections makes the router refuse to load whichever it sees second.
	dirCounts := map[string]int{}
	for _, m := range models {
		cfg, ok := configs[m.ID]
		if !ok || !cfg.Enabled {
			continue
		}
		if d := autoDiscoveryName(modelsDir, m.FilePath); d != "" {
			dirCounts[d]++
		}
	}

	for _, m := range models {
		cfg, ok := configs[m.ID]
		if !ok || !cfg.Enabled {
			continue
		}

		sectionName := m.ID

		b.WriteString(fmt.Sprintf("[%s]\n", sectionName))
		b.WriteString(fmt.Sprintf("model = %s\n", m.FilePath))

		// Aliases: every name a client might use to reference this model.
		// The dirname is included only when it's unique to this model — for
		// multi-quant repos it'd collide with sibling sections.
		seen := map[string]bool{}
		aliasList := []string{}
		add := func(a string) {
			if a == "" || seen[a] {
				return
			}
			seen[a] = true
			aliasList = append(aliasList, a)
		}
		add(sectionName)
		if dn := autoDiscoveryName(modelsDir, m.FilePath); dn != "" && dirCounts[dn] == 1 {
			add(dn)
		}
		add(m.PublicName())
		for _, a := range cfg.Aliases {
			add(a)
		}
		b.WriteString(fmt.Sprintf("alias = %s\n", strings.Join(aliasList, ",")))

		isEmbed := IsEmbeddingModel(m.ModelID) || IsEmbeddingModel(m.ID)
		writeConfigParams(&b, cfg, isEmbed)
		b.WriteString("\n")
	}

	return b.String()
}

// autoDiscoveryName returns the name that --models-dir would assign to a
// model at the given path. Returns the first directory name under modelsDir.
func autoDiscoveryName(modelsDir, filePath string) string {
	rel, err := filepath.Rel(modelsDir, filePath)
	if err != nil {
		return ""
	}
	// rel is like "unsloth--Qwen3.5-27B-GGUF/Qwen3.5-27B-Q4_K_M.gguf"
	// or "unsloth--DeepSeek-R1-GGUF/UD-Q8_K_XL/model-00001.gguf"
	parts := strings.SplitN(rel, string(filepath.Separator), 2)
	if len(parts) == 0 {
		return ""
	}
	return parts[0]
}

func writeConfigParams(b *strings.Builder, cfg *ModelConfig, isEmbedding bool) {
	if !isEmbedding && cfg.ContextSize > 0 {
		b.WriteString(fmt.Sprintf("ctx-size = %d\n", cfg.ContextSize))
	}
	if cfg.GPULayers > 0 {
		b.WriteString(fmt.Sprintf("gpu-layers = %d\n", cfg.GPULayers))
	}
	if cfg.Threads > 0 {
		b.WriteString(fmt.Sprintf("threads = %d\n", cfg.Threads))
	}
	if cfg.Parallel > 1 {
		b.WriteString(fmt.Sprintf("parallel = %d\n", cfg.Parallel))
	}
	if cfg.TensorSplit != "" {
		b.WriteString(fmt.Sprintf("tensor-split = %s\n", cfg.TensorSplit))
	}
	if cfg.SplitMode != "" {
		b.WriteString(fmt.Sprintf("split-mode = %s\n", cfg.SplitMode))
	}
	if cfg.MainGPU > 0 {
		b.WriteString(fmt.Sprintf("main-gpu = %d\n", cfg.MainGPU))
	}
	if isEmbedding {
		b.WriteString("embeddings = true\n")
	}
	if !isEmbedding {
		if cfg.FlashAttention {
			b.WriteString("flash-attn = on\n")
		}
		if cfg.Jinja {
			b.WriteString("jinja = true\n")
		}
		if cfg.KVCacheQuant != "" {
			b.WriteString(fmt.Sprintf("cache-type-k = %s\n", cfg.KVCacheQuant))
			b.WriteString(fmt.Sprintf("cache-type-v = %s\n", cfg.KVCacheQuant))
		}
		if cfg.DirectIO {
			b.WriteString("direct-io = true\n")
		}
		if cfg.MmprojPath != "" {
			b.WriteString(fmt.Sprintf("mmproj = %s\n", cfg.MmprojPath))
		}
		// Speculative decoding. llama.cpp split the legacy mode-agnostic
		// flags (--draft-max, --draft-min, --spec-ngram-size-n/m) into
		// mode-specific flags. Emit the right name based on SpecType.
		switch cfg.SpecType {
		case "draft":
			b.WriteString("spec-type = draft-simple\n")
			if cfg.DraftModelPath != "" {
				b.WriteString(fmt.Sprintf("model-draft = %s\n", cfg.DraftModelPath))
			}
			if cfg.DraftMax > 0 {
				b.WriteString(fmt.Sprintf("spec-draft-n-max = %d\n", cfg.DraftMax))
			}
			if cfg.DraftMin > 0 {
				b.WriteString(fmt.Sprintf("spec-draft-n-min = %d\n", cfg.DraftMin))
			}
			if cfg.DraftPMin != "" {
				b.WriteString(fmt.Sprintf("spec-draft-p-min = %s\n", cfg.DraftPMin))
			}
			if cfg.DraftCtxSize > 0 {
				b.WriteString(fmt.Sprintf("ctx-size-draft = %d\n", cfg.DraftCtxSize))
			}
			if cfg.DraftGPULayers > 0 {
				b.WriteString(fmt.Sprintf("gpu-layers-draft = %d\n", cfg.DraftGPULayers))
			}
			if cfg.DraftDevice != "" {
				b.WriteString(fmt.Sprintf("device-draft = %s\n", cfg.DraftDevice))
			}
			if cfg.DraftCPUMoE > 0 {
				b.WriteString(fmt.Sprintf("n-cpu-moe-draft = %d\n", cfg.DraftCPUMoE))
			}
			if cfg.DraftKVCacheQuant != "" {
				b.WriteString(fmt.Sprintf("cache-type-k-draft = %s\n", cfg.DraftKVCacheQuant))
				b.WriteString(fmt.Sprintf("cache-type-v-draft = %s\n", cfg.DraftKVCacheQuant))
			}
		case "draft-mtp":
			b.WriteString("spec-type = draft-mtp\n")
			if cfg.DraftMax > 0 {
				b.WriteString(fmt.Sprintf("spec-draft-n-max = %d\n", cfg.DraftMax))
			}
			if cfg.DraftMin > 0 {
				b.WriteString(fmt.Sprintf("spec-draft-n-min = %d\n", cfg.DraftMin))
			}
			if cfg.DraftPMin != "" {
				b.WriteString(fmt.Sprintf("spec-draft-p-min = %s\n", cfg.DraftPMin))
			}
		case "ngram-mod":
			b.WriteString(fmt.Sprintf("spec-type = %s\n", cfg.SpecType))
			if cfg.DraftMax > 0 {
				b.WriteString(fmt.Sprintf("spec-ngram-mod-n-max = %d\n", cfg.DraftMax))
			}
			if cfg.DraftMin > 0 {
				b.WriteString(fmt.Sprintf("spec-ngram-mod-n-min = %d\n", cfg.DraftMin))
			}
		case "ngram-simple", "ngram-map-k", "ngram-map-k4v":
			b.WriteString(fmt.Sprintf("spec-type = %s\n", cfg.SpecType))
			prefix := "spec-" + cfg.SpecType
			if cfg.NgramSizeN > 0 {
				b.WriteString(fmt.Sprintf("%s-size-n = %d\n", prefix, cfg.NgramSizeN))
			}
			if cfg.NgramSizeM > 0 {
				b.WriteString(fmt.Sprintf("%s-size-m = %d\n", prefix, cfg.NgramSizeM))
			}
		case "ngram-cache":
			b.WriteString(fmt.Sprintf("spec-type = %s\n", cfg.SpecType))
		}
	}

	// Sampling parameters
	if cfg.Temperature != nil {
		b.WriteString(fmt.Sprintf("temp = %g\n", *cfg.Temperature))
	}
	if cfg.TopP != nil {
		b.WriteString(fmt.Sprintf("top-p = %g\n", *cfg.TopP))
	}
	if cfg.TopK != nil {
		b.WriteString(fmt.Sprintf("top-k = %d\n", *cfg.TopK))
	}
	if cfg.MinP != nil {
		b.WriteString(fmt.Sprintf("min-p = %g\n", *cfg.MinP))
	}
	if cfg.PresencePenalty != nil {
		b.WriteString(fmt.Sprintf("presence-penalty = %g\n", *cfg.PresencePenalty))
	}
	if cfg.RepeatPenalty != nil {
		b.WriteString(fmt.Sprintf("repeat-penalty = %g\n", *cfg.RepeatPenalty))
	}

	// Extra flags
	if cfg.ExtraFlags != "" {
		for _, flag := range strings.Fields(cfg.ExtraFlags) {
			flag = strings.TrimLeft(flag, "-")
			if parts := strings.SplitN(flag, "=", 2); len(parts) == 2 {
				b.WriteString(fmt.Sprintf("%s = %s\n", parts[0], parts[1]))
			} else {
				b.WriteString(fmt.Sprintf("%s = true\n", flag))
			}
		}
	}
}

// RouterName returns the model name that the llama.cpp router uses for
// load/unload operations. This is the INI section name written by
// GeneratePresetINI, which is now the registry ID — a unique-per-quant
// value. Aliases work for inference requests but NOT for /models/load
// and /models/unload, so callers wiring up explicit (un)load calls must
// use this name.
func (r *Registry) RouterName(id string) string {
	r.mu.RLock()
	defer r.mu.RUnlock()
	if _, ok := r.data.Models[id]; !ok {
		return id
	}
	return id
}

// ModelFilePath returns the GGUF file path for a model.
func (r *Registry) ModelFilePath(id string) string {
	r.mu.RLock()
	defer r.mu.RUnlock()
	m, ok := r.data.Models[id]
	if !ok {
		return ""
	}
	return m.FilePath
}

// WritePresetINI generates and writes the preset INI file to the data directory.
func (r *Registry) WritePresetINI() (string, error) {
	r.mu.RLock()
	models := make([]*Model, 0, len(r.data.Models))
	for _, m := range r.data.Models {
		models = append(models, m)
	}
	configs := r.data.Configs
	r.mu.RUnlock()

	content := GeneratePresetINI(r.modelsDir, models, configs)

	presetPath := filepath.Join(r.dataDir, "config", "preset.ini")
	os.MkdirAll(filepath.Dir(presetPath), 0o755)

	if err := os.WriteFile(presetPath, []byte(content), 0o644); err != nil {
		return "", fmt.Errorf("write preset: %w", err)
	}

	return presetPath, nil
}
