package models

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// GeneratePresetINI creates a llama.cpp preset INI file from the model
// registry. Each model gets a section with per-model settings.
//
// Section names match what --models-dir auto-discovery uses (the parent
// directory name of the GGUF file), so presets apply to both auto-discovered
// and explicitly loaded models. An alias is set to the registry ID so
// API routing works with either name.
//
// INI keys map directly to llama-server CLI flags with leading dashes removed.
func GeneratePresetINI(dataDir string, models []*Model, configs map[string]*ModelConfig) string {
	var b strings.Builder

	b.WriteString("# Auto-generated by llamactl — do not edit manually.\n")
	b.WriteString("# Changes here will be overwritten when model configs are saved.\n\n")

	modelsDir := filepath.Join(dataDir, "models")

	for _, m := range models {
		cfg, ok := configs[m.ID]
		if !ok || !cfg.Enabled {
			continue
		}

		// Determine the section name — should match what --models-dir
		// auto-discovery would assign:
		// - For /data/models/{dir}/{file}.gguf → section name is {dir}
		// - For /data/models/{dir}/{subdir}/{file}.gguf → auto-discovery
		//   won't find it (only 1 level deep), so we use model= path
		sectionName := autoDiscoveryName(modelsDir, m.FilePath)
		if sectionName == "" {
			sectionName = m.ID // fallback
		}

		b.WriteString(fmt.Sprintf("[%s]\n", sectionName))

		// Always include model path — needed for nested subdirectory models
		// that auto-discovery can't find, and harmless for ones it can.
		b.WriteString(fmt.Sprintf("model = %s\n", m.FilePath))

		// Set alias to our registry ID so API routing works with our names
		// Include both the section name and registry ID as aliases
		aliases := sectionName
		if m.ID != sectionName {
			aliases += "," + m.ID
		}
		b.WriteString(fmt.Sprintf("alias = %s\n", aliases))

		isEmbed := IsEmbeddingModel(m.ModelID) || IsEmbeddingModel(m.ID)
		writeConfigParams(&b, cfg, isEmbed)
		b.WriteString("\n")
	}

	return b.String()
}

// autoDiscoveryName returns the name that --models-dir would assign to a
// model at the given path. Returns the first directory name under modelsDir.
func autoDiscoveryName(modelsDir, filePath string) string {
	rel, err := filepath.Rel(modelsDir, filePath)
	if err != nil {
		return ""
	}
	// rel is like "unsloth--Qwen3.5-27B-GGUF/Qwen3.5-27B-Q4_K_M.gguf"
	// or "unsloth--DeepSeek-R1-GGUF/UD-Q8_K_XL/model-00001.gguf"
	parts := strings.SplitN(rel, string(filepath.Separator), 2)
	if len(parts) == 0 {
		return ""
	}
	return parts[0]
}

func writeConfigParams(b *strings.Builder, cfg *ModelConfig, isEmbedding bool) {
	if !isEmbedding && cfg.ContextSize > 0 {
		b.WriteString(fmt.Sprintf("ctx-size = %d\n", cfg.ContextSize))
	}
	if cfg.GPULayers > 0 {
		b.WriteString(fmt.Sprintf("gpu-layers = %d\n", cfg.GPULayers))
	}
	if cfg.Threads > 0 {
		b.WriteString(fmt.Sprintf("threads = %d\n", cfg.Threads))
	}
	if cfg.TensorSplit != "" {
		b.WriteString(fmt.Sprintf("tensor-split = %s\n", cfg.TensorSplit))
	}
	if isEmbedding {
		b.WriteString("embeddings = true\n")
	}
	if !isEmbedding {
		if cfg.FlashAttention {
			b.WriteString("flash-attn = on\n")
		}
		if cfg.Jinja {
			b.WriteString("jinja = true\n")
		}
		if cfg.KVCacheQuant != "" {
			b.WriteString(fmt.Sprintf("cache-type-k = %s\n", cfg.KVCacheQuant))
			b.WriteString(fmt.Sprintf("cache-type-v = %s\n", cfg.KVCacheQuant))
		}
		if cfg.DirectIO {
			b.WriteString("direct-io = true\n")
		}
		if cfg.MmprojPath != "" {
			b.WriteString(fmt.Sprintf("mmproj = %s\n", cfg.MmprojPath))
		}
		if cfg.DraftModelPath != "" {
			b.WriteString(fmt.Sprintf("model-draft = %s\n", cfg.DraftModelPath))
			if cfg.DraftMax > 0 {
				b.WriteString(fmt.Sprintf("draft-max = %d\n", cfg.DraftMax))
			}
			if cfg.DraftMin > 0 {
				b.WriteString(fmt.Sprintf("draft-min = %d\n", cfg.DraftMin))
			}
		}
	}

	// Sampling parameters
	if cfg.Temperature != nil {
		b.WriteString(fmt.Sprintf("temp = %g\n", *cfg.Temperature))
	}
	if cfg.TopP != nil {
		b.WriteString(fmt.Sprintf("top-p = %g\n", *cfg.TopP))
	}
	if cfg.TopK != nil {
		b.WriteString(fmt.Sprintf("top-k = %d\n", *cfg.TopK))
	}
	if cfg.MinP != nil {
		b.WriteString(fmt.Sprintf("min-p = %g\n", *cfg.MinP))
	}
	if cfg.PresencePenalty != nil {
		b.WriteString(fmt.Sprintf("presence-penalty = %g\n", *cfg.PresencePenalty))
	}
	if cfg.RepeatPenalty != nil {
		b.WriteString(fmt.Sprintf("repeat-penalty = %g\n", *cfg.RepeatPenalty))
	}

	// Extra flags
	if cfg.ExtraFlags != "" {
		for _, flag := range strings.Fields(cfg.ExtraFlags) {
			flag = strings.TrimLeft(flag, "-")
			if parts := strings.SplitN(flag, "=", 2); len(parts) == 2 {
				b.WriteString(fmt.Sprintf("%s = %s\n", parts[0], parts[1]))
			} else {
				b.WriteString(fmt.Sprintf("%s = true\n", flag))
			}
		}
	}
}

// RouterName returns the model name that the llama.cpp router uses for
// load/unload operations. This is the INI section name (the auto-discovery
// directory name), NOT the registry ID. Aliases work for inference requests
// but NOT for /models/load and /models/unload.
func (r *Registry) RouterName(id string) string {
	r.mu.RLock()
	defer r.mu.RUnlock()
	m, ok := r.data.Models[id]
	if !ok {
		return id // fallback to registry ID
	}
	modelsDir := filepath.Join(r.dataDir, "models")
	name := autoDiscoveryName(modelsDir, m.FilePath)
	if name == "" {
		return id
	}
	return name
}

// ModelFilePath returns the GGUF file path for a model.
func (r *Registry) ModelFilePath(id string) string {
	r.mu.RLock()
	defer r.mu.RUnlock()
	m, ok := r.data.Models[id]
	if !ok {
		return ""
	}
	return m.FilePath
}

// WritePresetINI generates and writes the preset INI file to the data directory.
func (r *Registry) WritePresetINI() (string, error) {
	r.mu.RLock()
	models := make([]*Model, 0, len(r.data.Models))
	for _, m := range r.data.Models {
		models = append(models, m)
	}
	configs := r.data.Configs
	r.mu.RUnlock()

	content := GeneratePresetINI(r.dataDir, models, configs)

	presetPath := filepath.Join(r.dataDir, "config", "preset.ini")
	os.MkdirAll(filepath.Dir(presetPath), 0o755)

	if err := os.WriteFile(presetPath, []byte(content), 0o644); err != nil {
		return "", fmt.Errorf("write preset: %w", err)
	}

	return presetPath, nil
}
